services:
  - type: web
    name: editorpack-api
    env: node
    region: singapore
    buildCommand: npm install --build-from-source
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: editorpack_super_secret_2025
      - key: NODE_VERSION
        value: 20.11.0
    disk:
      name: editorpack-data
      mountPath: /data
      sizeGB: 1
